-- For table REGION

ALTER TABLE REGION
ADD CONSTRAINT region_pkey PRIMARY KEY (R_REGIONKEY);

-- For table NATION

ALTER TABLE NATION
ADD CONSTRAINT nation_pkey PRIMARY KEY (N_NATIONKEY);

ALTER TABLE NATION
ADD CONSTRAINT nation_region_fk FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY);


-- For table PART
ALTER TABLE part
ADD CONSTRAINT part_pkey PRIMARY KEY (P_PARTKEY);


-- For table SUPPLIER
ALTER TABLE supplier
ADD CONSTRAINT supplier_pkey PRIMARY KEY (S_SUPPKEY);

ALTER TABLE supplier
ADD CONSTRAINT supplier_nation_fk FOREIGN KEY (S_NATIONKEY) REFERENCES nation(N_NATIONKEY);


-- For table PARTSUPP
ALTER TABLE partsupp
ADD CONSTRAINT partsupp_pkey PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY);


-- For table CUSTOMER
ALTER TABLE customer
ADD CONSTRAINT customer_pkey PRIMARY KEY (C_CUSTKEY);

ALTER TABLE customer
ADD CONSTRAINT customer_nation_fk FOREIGN KEY (C_NATIONKEY) REFERENCES nation(N_NATIONKEY);


-- For table LINEITEM
ALTER TABLE lineitem
ADD CONSTRAINT lineitem_pkey PRIMARY KEY (L_ORDERKEY, L_LINENUMBER);


-- For table ORDERS
ALTER TABLE orders
ADD CONSTRAINT orders_pkey PRIMARY KEY (O_ORDERKEY);
CREATE INDEX ON orders(O_CUSTKEY);

-- For table PARTSUPP
ALTER TABLE partsupp
ADD CONSTRAINT partsupp_supplier_fk FOREIGN KEY (PS_SUPPKEY) REFERENCES supplier(S_SUPPKEY);

ALTER TABLE partsupp
ADD CONSTRAINT partsupp_part_fk FOREIGN KEY (PS_PARTKEY) REFERENCES part(P_PARTKEY);

-- For table ORDERS
ALTER TABLE orders
ADD CONSTRAINT orders_customer_fk FOREIGN KEY (O_CUSTKEY) REFERENCES customer(C_CUSTKEY);

-- For table LINEITEM
ALTER TABLE lineitem
ADD CONSTRAINT lineitem_order_fk FOREIGN KEY (L_ORDERKEY) REFERENCES orders(O_ORDERKEY);

ALTER TABLE lineitem
ADD CONSTRAINT lineitem_partsupp_fk FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES partsupp(PS_PARTKEY, PS_SUPPKEY);

CREATE INDEX ON lineitem(l_shipdate);
CREATE INDEX ON lineitem(l_partkey);
CREATE INDEX ON lineitem(l_suppkey);
