EXPLAIN ANALYZE
SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS REVENUE
FROM  
    LINEORDER AS lo,
    DATE AS d,
    SUPPLIER AS s,
    PART AS p,
    CUSTOMER AS c
WHERE 
    LO_ORDERDATE = D_DATEKEY
    AND D_YEAR = 1993
    AND LO_DISCOUNT BETWEEN 1 AND 3
    AND LO_QUANTITY < 25

    AND LO_SUPPKEY = S_SUPPKEY
    AND LO_PARTKEY = P_PARTKEY
    AND LO_CUSTKEY = C_CUSTKEY
    AND (-1399.598 + 3.687 * c.c_age + 1.844 * d.d_luck + 7.377 * p.p_percent + 3.687 * s.s_scale) >= 0.0;