EXPLAIN ANALYZE
SELECT SUM(LO_EXTENDEDPRICE * LO_DISCOUNT) AS REVENUE
FROM 
    DATE AS d CROSS JOIN
    LINEORDER AS lo CROSS JOIN
    SUPPLIER AS s CROSS JOIN
    PART AS p CROSS JOIN
    CUSTOMER AS c
WHERE 
    LO_ORDERDATE = D_DATEKEY
    AND D_YEARMONTH = 'Jan1994'
    AND LO_DISCOUNT BETWEEN 4 AND 6
    AND LO_QUANTITY BETWEEN 26 AND 35
    AND LO_SUPPKEY = S_SUPPKEY
    AND LO_PARTKEY = P_PARTKEY
    AND LO_CUSTKEY = C_CUSTKEY
    AND (-1399.598 + 3.687 * c.c_age + 1.844 * d.d_luck + 7.377 * p.p_percent + 3.687 * s.s_scale) >= 0.0;