EXPLAIN ANALYZE
SELECT C_CITY, S_CITY, D_YEAR, SUM(LO_REVENUE)
AS  REVENUE
FROM
    LINEORDER AS lo,
    DATE AS d,
    SUPPLIER AS s,
    PART AS p,
    CUSTOMER AS c
WHERE  
    LO_CUSTKEY = C_CUSTKEY
    AND LO_SUPPKEY = S_SUPPKEY
    AND  LO_ORDERDATE = D_DATEKEY
    AND LO_PARTKEY = P_PARTKEY
    AND (-1399.598 + 3.687 * c.c_age + 1.844 * d.d_luck + 7.377 * p.p_percent + 3.687 * s.s_scale) >= 0.0
    AND (C_CITY='UNITED KI1' OR C_CITY='UNITED KI5')
    AND (S_CITY='UNITED KI1' OR S_CITY='UNITED KI5')
    AND D_YEAR >= 1992 AND D_YEAR <= 1997
    GROUP BY C_CITY, S_CITY, D_YEAR
    ORDER BY D_YEAR ASC,  REVENUE DESC;
