EXPLAIN ANALYZE
SELECT D_YEAR, C_NATION,
SUM(LO_REVENUE - LO_SUPPLYCOST) AS PROFIT
FROM 
    LINEORDER AS lo,
    DATE AS d,
    SUPPLIER AS s,
    PART AS p,
    CUSTOMER AS c
WHERE 
    LO_CUSTKEY = C_CUSTKEY
    AND LO_SUPPKEY = S_SUPPKEY
    AND LO_PARTKEY = P_PARTKEY
    AND  LO_ORDERDATE = D_DATEKEY
    AND C_REGION = 'AMERICA'
    AND S_REGION = 'AMERICA'
    AND (P_MFGR = 'MFGR#1' OR P_MFGR = 'MFGR#2')
    AND (-1399.598 + 3.687 * c.c_age + 1.844 * d.d_luck + 7.377 * p.p_percent + 3.687 * s.s_scale) >= 0.0
GROUP BY D_YEAR, C_NATION
ORDER BY D_YEAR, C_NATION;