EXPLAIN ANALYZE
SELECT D_YEAR, S_CITY, P_BRAND1,
SUM(LO_REVENUE - LO_SUPPLYCOST) AS PROFIT
FROM 
    LINEORDER AS lo,
    DATE AS d,
    SUPPLIER AS s,
    PART AS p,
    CUSTOMER AS c
WHERE  
    LO_CUSTKEY = C_CUSTKEY
    AND LO_SUPPKEY = S_SUPPKEY
    AND LO_PARTKEY = P_PARTKEY
    AND  LO_ORDERDATE = D_DATEKEY
    AND S_NATION = 'UNITED STATES'
    AND (D_YEAR = 1997 OR D_YEAR = 1998)
    AND P_CATEGORY = 'MFGR#14'
    AND (-1399.598 + 3.687 * c.c_age + 1.844 * d.d_luck + 7.377 * p.p_percent + 3.687 * s.s_scale) >= 0.0
GROUP BY D_YEAR, S_CITY, P_BRAND1
ORDER BY D_YEAR, S_CITY, P_BRAND1;